CREATE TABLE IF NOT EXISTS users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE, password_hash TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS favorites (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 key VARCHAR(255) NOT NULL, source VARCHAR(32) NOT NULL, name VARCHAR(300) NOT NULL,
 scientific_name VARCHAR(300), image TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(user_id, source, key));
CREATE INDEX IF NOT EXISTS idx_favorites_user_created ON favorites(user_id, created_at DESC);
CREATE TABLE IF NOT EXISTS ai_conversations (
 id VARCHAR(64) PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
 session_id VARCHAR(128) NOT NULL, assistant_type VARCHAR(20) NOT NULL
 CHECK (assistant_type IN ('SPECIES','TOUR_GUIDE')), title VARCHAR(100),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_owner
 ON ai_conversations(user_id, session_id, assistant_type, updated_at DESC);
CREATE TABLE IF NOT EXISTS ai_messages (
 id VARCHAR(64) PRIMARY KEY, conversation_id VARCHAR(64) NOT NULL
 REFERENCES ai_conversations(id) ON DELETE CASCADE, role VARCHAR(10) NOT NULL
 CHECK (role IN ('user','assistant')), content TEXT NOT NULL,
 metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_ai_messages_conversation
 ON ai_messages(conversation_id, created_at, id);
CREATE TABLE IF NOT EXISTS ai_usage (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 conversation_id VARCHAR(64) NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE,
 assistant_type VARCHAR(20) NOT NULL, input_chars INTEGER NOT NULL CHECK(input_chars>=0),
 output_chars INTEGER NOT NULL CHECK(output_chars>=0),
 estimated_input_tokens INTEGER NOT NULL CHECK(estimated_input_tokens>=0),
 estimated_output_tokens INTEGER NOT NULL CHECK(estimated_output_tokens>=0),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_ai_usage_conversation ON ai_usage(conversation_id, created_at DESC);
CREATE TABLE IF NOT EXISTS ai_feedback (
 id VARCHAR(64) PRIMARY KEY, message_id VARCHAR(64) NOT NULL
 REFERENCES ai_messages(id) ON DELETE CASCADE, rating SMALLINT NOT NULL CHECK(rating IN (-1,1)),
 comment VARCHAR(2000), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_message ON ai_feedback(message_id);
