-- Authenticated travel workspace: trips, personalized plans, budgets, activity, and search.
CREATE TABLE IF NOT EXISTS saved_trips (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 title VARCHAR(160) NOT NULL,
 resource_type VARCHAR(32), resource_id VARCHAR(255), destination VARCHAR(200),
 start_date DATE, end_date DATE,
 travelers INTEGER NOT NULL DEFAULT 1 CHECK (travelers BETWEEN 1 AND 100),
 notes VARCHAR(5000) NOT NULL DEFAULT '', itinerary JSONB NOT NULL DEFAULT '{}'::jsonb,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_saved_trips_user_updated ON saved_trips(user_id, updated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_saved_trips_resource_unique
 ON saved_trips(user_id, resource_type, resource_id) WHERE resource_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS trip_plans (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 saved_trip_id BIGINT REFERENCES saved_trips(id) ON DELETE SET NULL,
 conversation_id VARCHAR(64) REFERENCES ai_conversations(id) ON DELETE SET NULL,
 title VARCHAR(160) NOT NULL, destination VARCHAR(200) NOT NULL,
 inputs JSONB NOT NULL DEFAULT '{}'::jsonb,
 plan_text TEXT NOT NULL CHECK (char_length(plan_text) <= 100000),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_trip_plans_user_updated ON trip_plans(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS budget_plans (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 saved_trip_id BIGINT REFERENCES saved_trips(id) ON DELETE SET NULL,
 title VARCHAR(160) NOT NULL, currency CHAR(3) NOT NULL,
 target_minor BIGINT NOT NULL DEFAULT 0 CHECK (target_minor >= 0),
 travelers INTEGER NOT NULL DEFAULT 1 CHECK (travelers BETWEEN 1 AND 100),
 duration_days INTEGER NOT NULL DEFAULT 1 CHECK (duration_days BETWEEN 1 AND 365),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_budget_plans_user_updated ON budget_plans(user_id, updated_at DESC);
CREATE TABLE IF NOT EXISTS budget_expenses (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 budget_plan_id BIGINT NOT NULL REFERENCES budget_plans(id) ON DELETE CASCADE,
 category VARCHAR(64) NOT NULL, label VARCHAR(120) NOT NULL,
 amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0), position INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_budget_expenses_plan ON budget_expenses(budget_plan_id, position, id);

CREATE TABLE IF NOT EXISTS user_activity (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 event_type VARCHAR(48) NOT NULL, resource_type VARCHAR(32), resource_id VARCHAR(255),
 label VARCHAR(300) NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_activity_user_created ON user_activity(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS search_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 query VARCHAR(300) NOT NULL, scope VARCHAR(32) NOT NULL DEFAULT 'site',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_search_history_user_created ON search_history(user_id, created_at DESC);