import { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { deleteConversation, getConversation, listConversations, renameConversation, sendFeedback, streamAssistantChat, type AssistantType, type ChatMessage, type ConversationSummary } from '../../services/assistantApi';
import { useAuth } from '../../context/auth';
import { createTripPlan } from '../../services/accountApi';
import { notify } from '../../utils/notifications';
import AssistantHeader from './AssistantHeader';
import ChatInput from './ChatInput';
import ChatWindow from './ChatWindow';
import ConversationSidebar from './ConversationSidebar';
import TripPlannerForm, { type TripPlannerValues } from './TripPlannerForm';
import { assistantPresentations } from './config';
import './assistant.css';

interface Props { assistantType: AssistantType; initialPrompt?: string; }
const WorldSphereAssistant=({assistantType,initialPrompt=''}:Props)=>{
 const config=assistantPresentations[assistantType];const {isAuthenticated}=useAuth();const navigate=useNavigate();
 const [messages,setMessages]=useState<ChatMessage[]>([]);const [conversationId,setConversationId]=useState<string>();const [conversations,setConversations]=useState<ConversationSummary[]>([]);const [historyLoading,setHistoryLoading]=useState(true);const [sidebarOpen,setSidebarOpen]=useState(false);const [streaming,setStreaming]=useState(false);const [error,setError]=useState('');const [lastPlanInput,setLastPlanInput]=useState<TripPlannerValues|null>(null);const abortRef=useRef<AbortController|null>(null);const inFlightRef=useRef(false);const plannerContext=useRef<TripPlannerValues|null>(null);
 const refreshHistory=useCallback(async()=>{setHistoryLoading(true);try{setConversations(await listConversations(assistantType))}catch{setConversations([])}finally{setHistoryLoading(false)}},[assistantType]);
 useEffect(()=>{let active=true;listConversations(assistantType).then(items=>{if(active)setConversations(items)}).catch(()=>{if(active)setConversations([])}).finally(()=>{if(active)setHistoryLoading(false)});return()=>{active=false}},[assistantType]);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('conversation');if(!id)return;getConversation(id,assistantType).then(c=>{setConversationId(id);setMessages(c.messages)}).catch(err=>setError(err instanceof Error?err.message:'Could not load this conversation.'))},[assistantType]);
 useEffect(()=>()=>{abortRef.current?.abort()},[]);
 const load=async(id:string)=>{if(streaming)return;setError('');try{const c=await getConversation(id,assistantType);setConversationId(id);setMessages(c.messages);setSidebarOpen(false)}catch(err){setError(err instanceof Error?err.message:'Could not load this conversation.')}};
 const send=useCallback(async(text:string,baseMessages?:ChatMessage[])=>{if(inFlightRef.current)return;inFlightRef.current=true;const history=baseMessages??messages;const userMessage:ChatMessage={role:'user',content:text};const requestMessages=[...history,userMessage].filter(item=>item.content.trim());setMessages([...requestMessages,{role:'assistant',content:''}]);setError('');setStreaming(true);const controller=new AbortController();abortRef.current=controller;try{await streamAssistantChat({assistantType,conversationId,messages:requestMessages,context:plannerContext.current?{tripPlanner:plannerContext.current}:undefined},{signal:controller.signal,onConversation:setConversationId,onChunk:chunk=>setMessages(current=>current.map((item,index)=>index===current.length-1?{...item,content:item.content+chunk}:item))});void refreshHistory()}catch(err){if(err instanceof DOMException&&err.name==='AbortError')return;setError(err instanceof Error?err.message:'Something went wrong asking WorldSphere AI.');setMessages(current=>current.filter((item,index)=>!(index===current.length-1&&item.role==='assistant'&&!item.content)))}finally{setStreaming(false);inFlightRef.current=false;abortRef.current=null;plannerContext.current=null}},[assistantType,conversationId,messages,refreshHistory]);
 const newChat=()=>{abortRef.current?.abort();setConversationId(undefined);setMessages([]);setError('');setLastPlanInput(null);setSidebarOpen(false)};
 const retry=()=>{const index=messages.map(item=>item.role).lastIndexOf('user');if(index>=0)send(messages[index].content,messages.slice(0,index))};
 const rename=async(c:ConversationSummary)=>{const title=window.prompt('Rename conversation',c.title||'');if(!title?.trim())return;await renameConversation(c.id,assistantType,title.trim());await refreshHistory()};
 const remove=async(c:ConversationSummary)=>{if(!window.confirm(`Delete “${c.title||'this conversation'}”?`))return;await deleteConversation(c.id,assistantType);if(c.id===conversationId)newChat();await refreshHistory()};
 const plan=(prompt:string,values:TripPlannerValues)=>{plannerContext.current=values;setLastPlanInput(values);send(prompt)};
 const savePlan=async()=>{const answer=[...messages].reverse().find(item=>item.role==='assistant'&&item.content.trim())?.content;if(!lastPlanInput||!answer)return;const destination=lastPlanInput.destinations||lastPlanInput.startingCity||'Kenya';const payload={title:`${destination} personalized plan`,destination,conversationId,inputs:lastPlanInput as unknown as Record<string,unknown>,planText:answer};if(!isAuthenticated){sessionStorage.setItem('worldsphere_pending_plan',JSON.stringify(payload));const returnTo=`${window.location.pathname}${window.location.search}`;sessionStorage.setItem('worldsphere_auth_return',returnTo);navigate('/login',{state:{from:returnTo}});return}try{await createTripPlan(payload);notify('Personalized trip plan saved.')}catch(err){notify(err instanceof Error?err.message:'Could not save plan.','error')}};
 return <section className={`worldsphere-assistant worldsphere-assistant--${assistantType.toLowerCase()}`} style={{'--assistant-accent':config.accent} as React.CSSProperties}><ConversationSidebar conversations={conversations} currentId={conversationId} open={sidebarOpen} loading={historyLoading} onClose={()=>setSidebarOpen(false)} onOpen={load} onRename={rename} onDelete={remove}/>{sidebarOpen&&<button className="assistant-sidebar-backdrop" onClick={()=>setSidebarOpen(false)} aria-label="Close history"/>}<div className="assistant-main"><AssistantHeader config={config} onNewChat={newChat} onToggleSidebar={()=>setSidebarOpen(value=>!value)}/>{assistantType==='TOUR_GUIDE'&&<TripPlannerForm onPlan={plan} disabled={streaming}/>}<div className="assistant-scroll"><ChatWindow config={config} messages={messages} streaming={streaming} onPrompt={send} onRetry={retry} onFeedback={(messageId,rating)=>sendFeedback(messageId,rating).catch(()=>undefined)}/>{error&&<div className="assistant-error" role="alert">{error}</div>}{assistantType==='TOUR_GUIDE'&&lastPlanInput&&messages.some(item=>item.role==='assistant'&&item.content.trim())&&<button className="assistant-save-plan" onClick={savePlan}>Save personalized plan</button>}</div><footer className="assistant-composer"><ChatInput placeholder={config.inputPlaceholder} disabled={streaming} streaming={streaming} initialValue={initialPrompt} onSend={send} onStop={()=>abortRef.current?.abort()}/><p>WorldSphere AI can make mistakes. Verify current prices, advisories, and conservation facts.</p></footer></div></section>;
};
export default WorldSphereAssistant;