/* Generated by scripts/generate-nairobi-attraction-images.mjs.
 * Re-run after adding, renaming or removing Nairobi attraction images.
 */
export type NairobiAttractionImageSet = {
  folder: string;
  hero: string | null;
  images: readonly string[];
};

export const nairobiAttractionImages = {
  "bomas-of-kenya": {
    "folder": "Bomas of Kenya",
    "hero": "/images/tourism/Nairobi/Bomas%20of%20Kenya/hero%20image.jpg",
    "images": [
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/bomas-of-kenya.jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/caption%20(1).jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/caption%20(2).jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/caption%20(3).jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/caption%20(4).jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/caption.jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/definitely-visit-for%20(1).jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/definitely-visit-for.jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/hero%20image.jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/kenyans-maintain-their.jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/nice-calming-place-to.jpg",
      "/images/tourism/Nairobi/Bomas%20of%20Kenya/nice-calming-place.jpg"
    ]
  },
  "giraffe-centre": {
    "folder": "Giraffe Centre",
    "hero": "/images/tourism/Nairobi/Giraffe%20Centre/hero%20image.jpg",
    "images": [
      "/images/tourism/Nairobi/Giraffe%20Centre/caption%20(1).jpg",
      "/images/tourism/Nairobi/Giraffe%20Centre/caption%20(2).jpg",
      "/images/tourism/Nairobi/Giraffe%20Centre/caption.jpg",
      "/images/tourism/Nairobi/Giraffe%20Centre/giraffes-in-the-center.jpg",
      "/images/tourism/Nairobi/Giraffe%20Centre/hero%20image.jpg",
      "/images/tourism/Nairobi/Giraffe%20Centre/outdoor-to-see-the-giraffes.jpg",
      "/images/tourism/Nairobi/Giraffe%20Centre/tourists-feeding-giraffes.jpg",
      "/images/tourism/Nairobi/Giraffe%20Centre/tres.jpg"
    ]
  },
  "karen-blixen-museum": {
    "folder": "Karen Blixen Museum",
    "hero": "/images/tourism/Nairobi/Karen%20Blixen%20Museum/hero%20image.jpg",
    "images": [
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/art.jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/caption%20(1).jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/caption%20(2).jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/caption.jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/farmen.jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/hero%20image.jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/how-many-are-ready-for.jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/i-had-a-farm-in-africa.jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/kettle.jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/resident-artist-joseph.jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/some-of-karen-s-tools.jpg",
      "/images/tourism/Nairobi/Karen%20Blixen%20Museum/tractor.jpg"
    ]
  },
  "karura-forest": {
    "folder": "Karura Forest",
    "hero": "/images/tourism/Nairobi/Karura%20Forest/hero%20image.jpg",
    "images": [
      "/images/tourism/Nairobi/Karura%20Forest/beautiful-narina-trogon.jpg",
      "/images/tourism/Nairobi/Karura%20Forest/caption%20(1).jpg",
      "/images/tourism/Nairobi/Karura%20Forest/caption.jpg",
      "/images/tourism/Nairobi/Karura%20Forest/forest.jpg",
      "/images/tourism/Nairobi/Karura%20Forest/harvey-s-duiker-in-karura.jpg",
      "/images/tourism/Nairobi/Karura%20Forest/hero%20image.jpg",
      "/images/tourism/Nairobi/Karura%20Forest/karura-forest-reserve.jpg",
      "/images/tourism/Nairobi/Karura%20Forest/monkey%20(1).jpg",
      "/images/tourism/Nairobi/Karura%20Forest/monkey.jpg",
      "/images/tourism/Nairobi/Karura%20Forest/the-caves.jpg"
    ]
  },
  "nairobi-national-museum": {
    "folder": "Nairobi National Museum",
    "hero": "/images/tourism/Nairobi/Nairobi%20National%20Museum/hero%20image.jpg",
    "images": [
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/0e.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/art-gallery-inside-the.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/b9.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/caption.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/diorama-in-the-human.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/guns.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/hero%20image.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/nairobi-national-museum%20(1).jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/nairobi-national-museum.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Museum/user-review-upload.jpg"
    ]
  },
  "nairobi-national-park": {
    "folder": "Nairobi National Park",
    "hero": "/images/tourism/Nairobi/Nairobi%20National%20Park/hero%20image.jpg",
    "images": [
      "/images/tourism/Nairobi/Nairobi%20National%20Park/51.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/bf.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/c0.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/c2.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/caption.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/couples-of-lions-in-nairobi.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/cubs.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/girafe.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/hartebeest.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/hero%20image.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/i-happened-to-accompany.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/lovely-buffalo-in-nairobi.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/nairobi-national-park.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/ostrich.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/rhinos.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/ry.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/souvenirs-de-nos-voyages.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/vantage-point-for-scanning.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/welcome-to-kenya-s-first.jpg",
      "/images/tourism/Nairobi/Nairobi%20National%20Park/zebra.jpg"
    ]
  },
  "nairobi-railway-museum": {
    "folder": "Nairobi Railway Museum",
    "hero": "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/hero%20image.jpg",
    "images": [
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/bike.jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/caption%20(1).jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/caption%20(2).jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/caption%20(3).jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/caption.jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/hero%20image.jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/kenya-railway-museum.jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/nairobi-railway-museum.jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/rail.jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/railway-museum.jpg",
      "/images/tourism/Nairobi/Nairobi%20Railway%20Museum/vic.jpg"
    ]
  },
  "national-archives": {
    "folder": "National Archives",
    "hero": "/images/tourism/Nairobi/National%20Archives/hero%20image.webp",
    "images": [
      "/images/tourism/Nairobi/National%20Archives/coat%20of%20arms.jpg",
      "/images/tourism/Nairobi/National%20Archives/cupboard-coastal-area.jpg",
      "/images/tourism/Nairobi/National%20Archives/filename-120703-nationalarchiv.jpg",
      "/images/tourism/Nairobi/National%20Archives/hero%20image.webp",
      "/images/tourism/Nairobi/National%20Archives/national-archives%20(1).jpg",
      "/images/tourism/Nairobi/National%20Archives/national-archives%20(2).jpg",
      "/images/tourism/Nairobi/National%20Archives/national-archives%20interior.jpg",
      "/images/tourism/Nairobi/National%20Archives/national-archives-nairobi.jpg",
      "/images/tourism/Nairobi/National%20Archives/national-archives.jpg",
      "/images/tourism/Nairobi/National%20Archives/nayional-archives-museum%20(1).jpg",
      "/images/tourism/Nairobi/National%20Archives/nayional-archives-museum.jpg",
      "/images/tourism/Nairobi/National%20Archives/p2150020-largejpg.jpg",
      "/images/tourism/Nairobi/National%20Archives/photo0jpg.jpg",
      "/images/tourism/Nairobi/National%20Archives/tom.jpg"
    ]
  },
  "ngong-hills": {
    "folder": "Ngong Hills",
    "hero": "/images/tourism/Nairobi/Ngong%20Hills/hero%20image.jpg",
    "images": [
      "/images/tourism/Nairobi/Ngong%20Hills/caption%20(1).jpg",
      "/images/tourism/Nairobi/Ngong%20Hills/caption%20(2).jpg",
      "/images/tourism/Nairobi/Ngong%20Hills/caption.jpg",
      "/images/tourism/Nairobi/Ngong%20Hills/hero%20image.jpg",
      "/images/tourism/Nairobi/Ngong%20Hills/lovely-view.jpg",
      "/images/tourism/Nairobi/Ngong%20Hills/memories-of-our-previous.jpg",
      "/images/tourism/Nairobi/Ngong%20Hills/ngong-hills%20(1).jpg",
      "/images/tourism/Nairobi/Ngong%20Hills/ngong-hills.jpg"
    ]
  },
  "sheldrick-wildlife-trust": {
    "folder": "Sheldrick Wildlife Trust",
    "hero": "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/hero%20image.jpg",
    "images": [
      "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/after-a-midday-milk-feed.jpg",
      "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/caption.jpg",
      "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/ele.jpg",
      "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/elephants.jpg",
      "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/hero%20image.jpg",
      "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/rescued-orphans-form.jpg",
      "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/the-elephants-heading.jpg",
      "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/the-orphan-elephants.jpg",
      "/images/tourism/Nairobi/Sheldrick%20Wildlife%20Trust/zebra.jpg"
    ]
  }
} as const satisfies Record<string, NairobiAttractionImageSet>;
